# Generated by Django 2.2.6 on 2020-05-27 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190117_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=200, unique=True, verbose_name='姓名')),
                ('Student_number', models.CharField(max_length=20, verbose_name='学号')),
                ('Student_class', models.CharField(max_length=20, verbose_name='班级')),
                ('Student_qiandao', models.CharField(max_length=20, verbose_name='签到情况')),
                ('Student_qiandao_time', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='签到时间')),
            ],
            options={
                'verbose_name': '姓名',
                'verbose_name_plural': '姓名',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=200, unique=True, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '姓名',
                'verbose_name_plural': '姓名',
            },
        ),
        migrations.RemoveField(
            model_name='cost_result',
            name='Pship_number',
        ),
        migrations.RemoveField(
            model_name='fuel_rent',
            name='Pship_number',
        ),
        migrations.RemoveField(
            model_name='pcargo',
            name='Pship_number',
        ),
        migrations.RemoveField(
            model_name='pport',
            name='Pship_number',
        ),
        migrations.RemoveField(
            model_name='pship_pport',
            name='Pship_number',
        ),
        migrations.DeleteModel(
            name='Budget_result',
        ),
        migrations.DeleteModel(
            name='Cost_result',
        ),
        migrations.DeleteModel(
            name='Fuel_rent',
        ),
        migrations.DeleteModel(
            name='Pcargo',
        ),
        migrations.DeleteModel(
            name='Pport',
        ),
        migrations.DeleteModel(
            name='Pship',
        ),
        migrations.DeleteModel(
            name='Pship_Pport',
        ),
    ]
