# Generated by Django 2.2.6 on 2020-05-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200527_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_password',
            field=models.CharField(default=0, max_length=200, unique=True, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
