# Generated by Django 2.2.6 on 2020-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_qiandao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_qiandao',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Student_qiandao_time',
        ),
        migrations.AddField(
            model_name='student',
            name='Student_sex',
            field=models.CharField(default=0, max_length=200, unique=True, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
